export { HomePage } from './Home.tsx';
export { SitemapPage } from './Sitemap.tsx';
export * from './dashboards';
export * from './projects';
export * from './news';
export * from './academy';
export * from './company';
export * from './equipments';
export * from './corporate';
export * from './userAccount';
export * from './authentication';
export * from './errors';
